version: "3.8"
services:
  backend-flask:
    environment:
      CONNECTION_URL: "postgresql://postgres:password@postgres:5432"
      FLASK_ENV: development
      FRONTEND_URL: http://localhost:3000
      BACKEND_URL: http://localhost:4567
      AWS_COGNITO_USER_POOL_ID: "us-east-1_um2Q5srdh"
      AWS_COGNITO_USER_POOL_CLIENT_ID: "3jg5rdejv4ael47hvjsnoborii"
      AWS_DEFAULT_REGION: "us-east-1"
    build: ./backend-flask
    ports:
      - "4567:4567"
    volumes:
      - ./backend-flask:/backend-flask
    depends_on:
      - postgres
  frontend-react-js:
    environment:
      REACT_APP_BACKEND_URL: http://localhost:4567
      REACT_APP_AWS_PROJECT_REGION: "us-east-1"
      REACT_APP_AWS_COGNITO_REGION: "us-east-1"
      REACT_APP_AWS_USER_POOLS_ID: "us-east-1_um2Q5srdh"
      REACT_APP_CLIENT_ID: "3jg5rdejv4ael47hvjsnoborii"
    build: ./frontend-react-js
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-react-js:/frontend-react-js

  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  
  postgres:
    image: postgres:16.1-alpine3.19
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cruddur
    ports:
      - 5433:5432
networks:
  internal-network:
    driver: bridge
    name: cruddur
